# Do NOT update manually; changes here will be overwritten by Copier
_commit: a39b200
_src_path: gh:open-synergy/ssi-addons-repo-template
dependency_installation_mode: OCA
generate_requirements_txt: true
include_aeroo_report: false
include_wkhtmltopdf: false
odoo_version: 14.0
rebel_module_groups: []
repo_description: opnsynid-project
repo_name: opnsynid-project
repo_slug: opnsynid-project
travis_apt_packages: []
travis_apt_sources: []
