# Copyright 2022 OpenSynergy Indonesia
# Copyright 2022 PT. Simetri Sinergi Indonesia
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

{
    "name": "Project Extension",
    "version": "14.0.3.5.0",
    "website": "https://simetri-sinergi.id",
    "author": "OpenSynergy Indonesia, PT. Simetri Sinergi Indonesia",
    "license": "AGPL-3",
    "installable": True,
    "depends": [
        "project_stage_state",
        "ssi_master_data_mixin",
        "ssi_transaction_confirm_mixin",
        "ssi_transaction_ready_mixin",
        "ssi_transaction_open_mixin",
        "ssi_transaction_done_mixin",
        "ssi_transaction_terminate_mixin",
        "ssi_transaction_cancel_mixin",
        "ssi_transaction_date_due_mixin",
        "base_automation",
    ],
    "data": [
        "security/ir_module_category_data.xml",
        "security/ir_module_category/project_deliverable.xml",
        "security/ir_module_category/project_phase.xml",
        "security/res_group_data.xml",
        "security/res_group/project_deliverable.xml",
        "security/res_group/project_phase.xml",
        "security/ir.model.access.csv",
        "security/ir_model_access/project_deliverable.xml",
        "security/ir_model_access/project_phase.xml",
        "security/ir_model_access_data.xml",
        "security/ir_rule_data.xml",
        "security/ir_rule/project_deliverable.xml",
        "security/ir_rule/project_phase.xml",
        "ir_sequence/project_deliverable.xml",
        "ir_sequence/project_phase.xml",
        "sequence_template/project_deliverable.xml",
        "sequence_template/project_phase.xml",
        "policy_template/project_deliverable.xml",
        "policy_template/project_phase.xml",
        "approval_template/project_deliverable.xml",
        "approval_template/project_phase.xml",
        "ir_action_server/project_deliverable.xml",
        "ir_action_server/project_phase.xml",
        "base_automation/project_delivarable.xml",
        "base_automation/project_phase.xml",
        "menu.xml",
        "wizards/create_sucessor_task.xml",
        "views/project_project_views.xml",
        "views/project_task_views.xml",
        "views/project_task_type_views.xml",
        "views/project_tags_views.xml",
        "views/project_delivery_type_views.xml",
        "views/project_delivery_type_category_views.xml",
        "views/project_milestone_views.xml",
        "views/project_deliverable_views.xml",
        "views/project_phase_views.xml",
        "views/mail_activity_type_views.xml",
    ],
    "demo": [],
}
